variables:
  METASMT_DEFAULT_SOLVERS: "--build boolector-2.4.1 --build lingeling-bbc-9230380-161217 --build minisat-git"

### templates for docker images

.ubuntu16_x86: &ubuntu16_x86
  image: m0elnx/ubuntu-32bit:latest
  tags:
  - docker

.ubuntu16: &ubuntu16
  image: ubuntu:xenial
  tags:
  - docker

.ubuntu14: &ubuntu14
  image: ubuntu:trusty
  tags:
  - docker

.debian8: &debian8
  image: debian:jessie
  tags:
  - docker

### template and jobs for the default build
.build_default:
  script: &build_default
  - apt-get -qq update
  - apt-get -qq -y upgrade
  - apt-get install -qq -y build-essential cmake git wget unzip zlib1g-dev python
  - NUM_JOBS=$[`nproc`-1]
  - if [ "$NUM_JOBS" -lt 1 ]; then NUM_JOBS=1; fi
  - git clone https://github.com/agra-uni-bremen/dependencies.git
  - if [ -z "$METASMT_SOLVERS" ]; then METASMT_SOLVERS=$METASMT_DEFAULT_SOLVERS; fi
  - ./bootstrap.sh -d deps -m RELEASE build $METASMT_SOLVERS
  - cd build
  - make -j $NUM_JOBS
  - ctest --output-on-failure --output-log tests.log || true
  - NUM_FAILED=`grep -o -E '[0-9]+ tests failed' tests.log | grep -o -E '[0-9]+'`
  - if [ -z "$MAX_FAILS" ]; then MAX_FAILS=10; fi
  - if [ "$NUM_FAILED" -gt "$MAX_FAILS" ]; then echo "Too many failures ($NUM_FAILED)"; exit 1; fi

build_default_ubuntu16:
  <<: *ubuntu16
  script: *build_default

build_default_ubuntu14:
  <<: *ubuntu14
  script: *build_default

build_default_debian8:
  <<: *debian8
  script: *build_default

build_default_ubuntu16_x86:
  <<: *ubuntu16_x86
  script: *build_default

### special build jobs
build_z3:
  <<: *ubuntu14
  variables:
    METASMT_SOLVERS: "--build Z3-4.5.0-x86-ubuntu-14.04-x64"
    MAX_FAILS: "4"
  script: *build_default

build_z3_x86:
  <<: *ubuntu16_x86
  variables:
    METASMT_SOLVERS: "--build Z3-4.5.0-x86-ubuntu-14.04-x86"
    MAX_FAILS: "4"
  script: *build_default

build_windows:
  script:
  - git submodule sync
  - git submodule update --init
  - call "%VS140COMNTOOLS%VsDevCmd.bat"
  - rmdir build /s /q
  - mkdir build
  - cd build
  - cmake .. -DBoost_USE_STATIC_LIBS=ON -DBOOST_ROOT="C:\deps\boost_1_60_0" -DZ3_DIR="C:\deps\z3-4.5.0-x86-win"
  - cmake --build . --config Debug
  - ctest
  tags:
  - windows
